// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: weaver/internal/grpc/weaver.proto

package weaver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workload messages
type CreateWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *WorkloadSpec          `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkloadRequest) Reset() {
	*x = CreateWorkloadRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkloadRequest) ProtoMessage() {}

func (x *CreateWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkloadRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkloadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateWorkloadRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateWorkloadRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type CreateWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        *WorkloadStatus        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkloadResponse) Reset() {
	*x = CreateWorkloadResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkloadResponse) ProtoMessage() {}

func (x *CreateWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkloadResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkloadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateWorkloadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkloadResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateWorkloadResponse) GetStatus() *WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateWorkloadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadRequest) Reset() {
	*x = GetWorkloadRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadRequest) ProtoMessage() {}

func (x *GetWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadResponse) Reset() {
	*x = GetWorkloadResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadResponse) ProtoMessage() {}

func (x *GetWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkloadResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelSelector map[string]string      `protobuf:"bytes,2,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ContinueToken string                 `protobuf:"bytes,4,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorkloadsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListWorkloadsRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

func (x *ListWorkloadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkloadsRequest) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*Workload            `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	ContinueToken string                 `protobuf:"bytes,2,opt,name=continue_token,json=continueToken,proto3" json:"continue_token,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkloadsResponse) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *ListWorkloadsResponse) GetContinueToken() string {
	if x != nil {
		return x.ContinueToken
	}
	return ""
}

func (x *ListWorkloadsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadRequest) Reset() {
	*x = DeleteWorkloadRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadRequest) ProtoMessage() {}

func (x *DeleteWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Provider messages
type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{7}
}

func (x *ListProvidersResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GetProviderRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRegionsRequest) Reset() {
	*x = GetProviderRegionsRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRegionsRequest) ProtoMessage() {}

func (x *GetProviderRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRegionsRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRegionsRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{8}
}

func (x *GetProviderRegionsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetProviderRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []string               `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRegionsResponse) Reset() {
	*x = GetProviderRegionsResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRegionsResponse) ProtoMessage() {}

func (x *GetProviderRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRegionsResponse.ProtoReflect.Descriptor instead.
func (*GetProviderRegionsResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{9}
}

func (x *GetProviderRegionsResponse) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type GetProviderMachineTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderMachineTypesRequest) Reset() {
	*x = GetProviderMachineTypesRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderMachineTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderMachineTypesRequest) ProtoMessage() {}

func (x *GetProviderMachineTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderMachineTypesRequest.ProtoReflect.Descriptor instead.
func (*GetProviderMachineTypesRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{10}
}

func (x *GetProviderMachineTypesRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetProviderMachineTypesRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type GetProviderMachineTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineTypes  []*MachineType         `protobuf:"bytes,1,rep,name=machine_types,json=machineTypes,proto3" json:"machine_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderMachineTypesResponse) Reset() {
	*x = GetProviderMachineTypesResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderMachineTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderMachineTypesResponse) ProtoMessage() {}

func (x *GetProviderMachineTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderMachineTypesResponse.ProtoReflect.Descriptor instead.
func (*GetProviderMachineTypesResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{11}
}

func (x *GetProviderMachineTypesResponse) GetMachineTypes() []*MachineType {
	if x != nil {
		return x.MachineTypes
	}
	return nil
}

type MachineType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           string                 `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu           string                 `protobuf:"bytes,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
	PricePerHour  float64                `protobuf:"fixed64,5,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineType) Reset() {
	*x = MachineType{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineType) ProtoMessage() {}

func (x *MachineType) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineType.ProtoReflect.Descriptor instead.
func (*MachineType) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{12}
}

func (x *MachineType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineType) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *MachineType) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *MachineType) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *MachineType) GetPricePerHour() float64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

// Scheduler messages
type GetSchedulerStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProvidersCount  int32                  `protobuf:"varint,2,opt,name=providers_count,json=providersCount,proto3" json:"providers_count,omitempty"`
	SchedulerStatus string                 `protobuf:"bytes,3,opt,name=scheduler_status,json=schedulerStatus,proto3" json:"scheduler_status,omitempty"`
	SchedulerError  string                 `protobuf:"bytes,4,opt,name=scheduler_error,json=schedulerError,proto3" json:"scheduler_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSchedulerStatusResponse) Reset() {
	*x = GetSchedulerStatusResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerStatusResponse) ProtoMessage() {}

func (x *GetSchedulerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSchedulerStatusResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{13}
}

func (x *GetSchedulerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSchedulerStatusResponse) GetProvidersCount() int32 {
	if x != nil {
		return x.ProvidersCount
	}
	return 0
}

func (x *GetSchedulerStatusResponse) GetSchedulerStatus() string {
	if x != nil {
		return x.SchedulerStatus
	}
	return ""
}

func (x *GetSchedulerStatusResponse) GetSchedulerError() string {
	if x != nil {
		return x.SchedulerError
	}
	return ""
}

type ScheduleWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *WorkloadSpec          `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Constraints   *PlacementConstraints  `protobuf:"bytes,2,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkloadRequest) Reset() {
	*x = ScheduleWorkloadRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkloadRequest) ProtoMessage() {}

func (x *ScheduleWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkloadRequest.ProtoReflect.Descriptor instead.
func (*ScheduleWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{14}
}

func (x *ScheduleWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ScheduleWorkloadRequest) GetConstraints() *PlacementConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type ScheduleWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EstimatedCost float64                `protobuf:"fixed64,5,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkloadResponse) Reset() {
	*x = ScheduleWorkloadResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkloadResponse) ProtoMessage() {}

func (x *ScheduleWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkloadResponse.ProtoReflect.Descriptor instead.
func (*ScheduleWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{15}
}

func (x *ScheduleWorkloadResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ScheduleWorkloadResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ScheduleWorkloadResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ScheduleWorkloadResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ScheduleWorkloadResponse) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *WorkloadSpec          `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Constraints   *PlacementConstraints  `protobuf:"bytes,2,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{16}
}

func (x *GetRecommendationsRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GetRecommendationsRequest) GetConstraints() *PlacementConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type GetRecommendationsResponse struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Recommendations []*ScheduleRecommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{17}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*ScheduleRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type ScheduleRecommendation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Provider         string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region           string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone             string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	CostPerHour      float64                `protobuf:"fixed64,4,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"`
	PerformanceScore float64                `protobuf:"fixed64,5,opt,name=performance_score,json=performanceScore,proto3" json:"performance_score,omitempty"`
	Reason           string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScheduleRecommendation) Reset() {
	*x = ScheduleRecommendation{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRecommendation) ProtoMessage() {}

func (x *ScheduleRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRecommendation.ProtoReflect.Descriptor instead.
func (*ScheduleRecommendation) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{18}
}

func (x *ScheduleRecommendation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ScheduleRecommendation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ScheduleRecommendation) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ScheduleRecommendation) GetCostPerHour() float64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

func (x *ScheduleRecommendation) GetPerformanceScore() float64 {
	if x != nil {
		return x.PerformanceScore
	}
	return 0
}

func (x *ScheduleRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetSchedulerStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalWorkloads      int32                  `protobuf:"varint,1,opt,name=total_workloads,json=totalWorkloads,proto3" json:"total_workloads,omitempty"`
	RunningWorkloads    int32                  `protobuf:"varint,2,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`
	PendingWorkloads    int32                  `protobuf:"varint,3,opt,name=pending_workloads,json=pendingWorkloads,proto3" json:"pending_workloads,omitempty"`
	FailedWorkloads     int32                  `protobuf:"varint,4,opt,name=failed_workloads,json=failedWorkloads,proto3" json:"failed_workloads,omitempty"`
	WorkloadsByProvider map[string]int32       `protobuf:"bytes,5,rep,name=workloads_by_provider,json=workloadsByProvider,proto3" json:"workloads_by_provider,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalCostPerHour    float64                `protobuf:"fixed64,6,opt,name=total_cost_per_hour,json=totalCostPerHour,proto3" json:"total_cost_per_hour,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSchedulerStatsResponse) Reset() {
	*x = GetSchedulerStatsResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchedulerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchedulerStatsResponse) ProtoMessage() {}

func (x *GetSchedulerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchedulerStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSchedulerStatsResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{19}
}

func (x *GetSchedulerStatsResponse) GetTotalWorkloads() int32 {
	if x != nil {
		return x.TotalWorkloads
	}
	return 0
}

func (x *GetSchedulerStatsResponse) GetRunningWorkloads() int32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *GetSchedulerStatsResponse) GetPendingWorkloads() int32 {
	if x != nil {
		return x.PendingWorkloads
	}
	return 0
}

func (x *GetSchedulerStatsResponse) GetFailedWorkloads() int32 {
	if x != nil {
		return x.FailedWorkloads
	}
	return 0
}

func (x *GetSchedulerStatsResponse) GetWorkloadsByProvider() map[string]int32 {
	if x != nil {
		return x.WorkloadsByProvider
	}
	return nil
}

func (x *GetSchedulerStatsResponse) GetTotalCostPerHour() float64 {
	if x != nil {
		return x.TotalCostPerHour
	}
	return 0
}

type PlacementConstraints struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region         string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone           string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	NodeLabels     map[string]string      `protobuf:"bytes,4,rep,name=node_labels,json=nodeLabels,proto3" json:"node_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tolerations    []*Toleration          `protobuf:"bytes,5,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	MaxCostPerHour float64                `protobuf:"fixed64,6,opt,name=max_cost_per_hour,json=maxCostPerHour,proto3" json:"max_cost_per_hour,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlacementConstraints) Reset() {
	*x = PlacementConstraints{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementConstraints) ProtoMessage() {}

func (x *PlacementConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementConstraints.ProtoReflect.Descriptor instead.
func (*PlacementConstraints) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{20}
}

func (x *PlacementConstraints) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PlacementConstraints) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlacementConstraints) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PlacementConstraints) GetNodeLabels() map[string]string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

func (x *PlacementConstraints) GetTolerations() []*Toleration {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *PlacementConstraints) GetMaxCostPerHour() float64 {
	if x != nil {
		return x.MaxCostPerHour
	}
	return 0
}

// Health check
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Core types
type Workload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Spec          *WorkloadSpec          `protobuf:"bytes,6,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *WorkloadStatus        `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{22}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Workload) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Workload) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Workload) GetStatus() *WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Workload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workload) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Workload) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources     *ResourceRequests      `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Volumes       []*VolumeMount         `protobuf:"bytes,6,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Ports         []*Port                `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	Sidecars      []*SidecarSpec         `protobuf:"bytes,8,rep,name=sidecars,proto3" json:"sidecars,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,9,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	Placement     *PlacementSpec         `protobuf:"bytes,10,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{23}
}

func (x *WorkloadSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *WorkloadSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WorkloadSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WorkloadSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *WorkloadSpec) GetResources() *ResourceRequests {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkloadSpec) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *WorkloadSpec) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *WorkloadSpec) GetSidecars() []*SidecarSpec {
	if x != nil {
		return x.Sidecars
	}
	return nil
}

func (x *WorkloadSpec) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *WorkloadSpec) GetPlacement() *PlacementSpec {
	if x != nil {
		return x.Placement
	}
	return nil
}

type ResourceRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu           string                 `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequests) Reset() {
	*x = ResourceRequests{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequests) ProtoMessage() {}

func (x *ResourceRequests) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequests.ProtoReflect.Descriptor instead.
func (*ResourceRequests) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{24}
}

func (x *ResourceRequests) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceRequests) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourceRequests) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ContentId     string                 `protobuf:"bytes,4,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{25}
}

func (x *VolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *VolumeMount) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{26}
}

func (x *Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Port) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type SidecarSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidecarSpec) Reset() {
	*x = SidecarSpec{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarSpec) ProtoMessage() {}

func (x *SidecarSpec) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarSpec.ProtoReflect.Descriptor instead.
func (*SidecarSpec) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{27}
}

func (x *SidecarSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SidecarSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SidecarSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SidecarSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SidecarSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type PlacementSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	NodeLabels    map[string]string      `protobuf:"bytes,4,rep,name=node_labels,json=nodeLabels,proto3" json:"node_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tolerations   []*Toleration          `protobuf:"bytes,5,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementSpec) Reset() {
	*x = PlacementSpec{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementSpec) ProtoMessage() {}

func (x *PlacementSpec) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementSpec.ProtoReflect.Descriptor instead.
func (*PlacementSpec) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{28}
}

func (x *PlacementSpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PlacementSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlacementSpec) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PlacementSpec) GetNodeLabels() map[string]string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

func (x *PlacementSpec) GetTolerations() []*Toleration {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

type Toleration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Effect        string                 `protobuf:"bytes,4,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toleration) Reset() {
	*x = Toleration{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toleration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toleration) ProtoMessage() {}

func (x *Toleration) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toleration.ProtoReflect.Descriptor instead.
func (*Toleration) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{29}
}

func (x *Toleration) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Toleration) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Toleration) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Toleration) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

type WorkloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	RestartCount  int32                  `protobuf:"varint,6,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Provider      string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	TailscaleIp   string                 `protobuf:"bytes,9,opt,name=tailscale_ip,json=tailscaleIp,proto3" json:"tailscale_ip,omitempty"`
	ContainerId   string                 `protobuf:"bytes,10,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,11,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	LastSnapshot  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_snapshot,json=lastSnapshot,proto3" json:"last_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_internal_grpc_weaver_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_weaver_internal_grpc_weaver_proto_rawDescGZIP(), []int{30}
}

func (x *WorkloadStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WorkloadStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WorkloadStatus) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

func (x *WorkloadStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *WorkloadStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WorkloadStatus) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WorkloadStatus) GetTailscaleIp() string {
	if x != nil {
		return x.TailscaleIp
	}
	return ""
}

func (x *WorkloadStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WorkloadStatus) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *WorkloadStatus) GetLastSnapshot() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSnapshot
	}
	return nil
}

var File_weaver_internal_grpc_weaver_proto protoreflect.FileDescriptor

const file_weaver_internal_grpc_weaver_proto_rawDesc = "" +
	"\n" +
	"!weaver/internal/grpc/weaver.proto\x12\x06weaver\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x03\n" +
	"\x15CreateWorkloadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12(\n" +
	"\x04spec\x18\x03 \x01(\v2\x14.weaver.WorkloadSpecR\x04spec\x12A\n" +
	"\x06labels\x18\x04 \x03(\v2).weaver.CreateWorkloadRequest.LabelsEntryR\x06labels\x12P\n" +
	"\vannotations\x18\x05 \x03(\v2..weaver.CreateWorkloadRequest.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x16CreateWorkloadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12.\n" +
	"\x06status\x18\x04 \x01(\v2\x16.weaver.WorkloadStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"$\n" +
	"\x12GetWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13GetWorkloadResponse\x12,\n" +
	"\bworkload\x18\x01 \x01(\v2\x10.weaver.WorkloadR\bworkload\"\x8b\x02\n" +
	"\x14ListWorkloadsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12V\n" +
	"\x0elabel_selector\x18\x02 \x03(\v2/.weaver.ListWorkloadsRequest.LabelSelectorEntryR\rlabelSelector\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12%\n" +
	"\x0econtinue_token\x18\x04 \x01(\tR\rcontinueToken\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x15ListWorkloadsResponse\x12.\n" +
	"\tworkloads\x18\x01 \x03(\v2\x10.weaver.WorkloadR\tworkloads\x12%\n" +
	"\x0econtinue_token\x18\x02 \x01(\tR\rcontinueToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"'\n" +
	"\x15DeleteWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x15ListProvidersResponse\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\"7\n" +
	"\x19GetProviderRegionsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"6\n" +
	"\x1aGetProviderRegionsResponse\x12\x18\n" +
	"\aregions\x18\x01 \x03(\tR\aregions\"T\n" +
	"\x1eGetProviderMachineTypesRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"[\n" +
	"\x1fGetProviderMachineTypesResponse\x128\n" +
	"\rmachine_types\x18\x01 \x03(\v2\x13.weaver.MachineTypeR\fmachineTypes\"\x83\x01\n" +
	"\vMachineType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x04 \x01(\tR\x03gpu\x12$\n" +
	"\x0eprice_per_hour\x18\x05 \x01(\x01R\fpricePerHour\"\xb1\x01\n" +
	"\x1aGetSchedulerStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0fproviders_count\x18\x02 \x01(\x05R\x0eprovidersCount\x12)\n" +
	"\x10scheduler_status\x18\x03 \x01(\tR\x0fschedulerStatus\x12'\n" +
	"\x0fscheduler_error\x18\x04 \x01(\tR\x0eschedulerError\"\x83\x01\n" +
	"\x17ScheduleWorkloadRequest\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.weaver.WorkloadSpecR\x04spec\x12>\n" +
	"\vconstraints\x18\x02 \x01(\v2\x1c.weaver.PlacementConstraintsR\vconstraints\"\xa2\x01\n" +
	"\x18ScheduleWorkloadResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eestimated_cost\x18\x05 \x01(\x01R\restimatedCost\"\x85\x01\n" +
	"\x19GetRecommendationsRequest\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.weaver.WorkloadSpecR\x04spec\x12>\n" +
	"\vconstraints\x18\x02 \x01(\v2\x1c.weaver.PlacementConstraintsR\vconstraints\"f\n" +
	"\x1aGetRecommendationsResponse\x12H\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1e.weaver.ScheduleRecommendationR\x0frecommendations\"\xc9\x01\n" +
	"\x16ScheduleRecommendation\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\"\n" +
	"\rcost_per_hour\x18\x04 \x01(\x01R\vcostPerHour\x12+\n" +
	"\x11performance_score\x18\x05 \x01(\x01R\x10performanceScore\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xb0\x03\n" +
	"\x19GetSchedulerStatsResponse\x12'\n" +
	"\x0ftotal_workloads\x18\x01 \x01(\x05R\x0etotalWorkloads\x12+\n" +
	"\x11running_workloads\x18\x02 \x01(\x05R\x10runningWorkloads\x12+\n" +
	"\x11pending_workloads\x18\x03 \x01(\x05R\x10pendingWorkloads\x12)\n" +
	"\x10failed_workloads\x18\x04 \x01(\x05R\x0ffailedWorkloads\x12n\n" +
	"\x15workloads_by_provider\x18\x05 \x03(\v2:.weaver.GetSchedulerStatsResponse.WorkloadsByProviderEntryR\x13workloadsByProvider\x12-\n" +
	"\x13total_cost_per_hour\x18\x06 \x01(\x01R\x10totalCostPerHour\x1aF\n" +
	"\x18WorkloadsByProviderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xcd\x02\n" +
	"\x14PlacementConstraints\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12M\n" +
	"\vnode_labels\x18\x04 \x03(\v2,.weaver.PlacementConstraints.NodeLabelsEntryR\n" +
	"nodeLabels\x124\n" +
	"\vtolerations\x18\x05 \x03(\v2\x12.weaver.TolerationR\vtolerations\x12)\n" +
	"\x11max_cost_per_hour\x18\x06 \x01(\x01R\x0emaxCostPerHour\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcd\x04\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x124\n" +
	"\x06labels\x18\x04 \x03(\v2\x1c.weaver.Workload.LabelsEntryR\x06labels\x12C\n" +
	"\vannotations\x18\x05 \x03(\v2!.weaver.Workload.AnnotationsEntryR\vannotations\x12(\n" +
	"\x04spec\x18\x06 \x01(\v2\x14.weaver.WorkloadSpecR\x04spec\x12.\n" +
	"\x06status\x18\a \x01(\v2\x16.weaver.WorkloadStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x03\n" +
	"\fWorkloadSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12/\n" +
	"\x03env\x18\x04 \x03(\v2\x1d.weaver.WorkloadSpec.EnvEntryR\x03env\x126\n" +
	"\tresources\x18\x05 \x01(\v2\x18.weaver.ResourceRequestsR\tresources\x12-\n" +
	"\avolumes\x18\x06 \x03(\v2\x13.weaver.VolumeMountR\avolumes\x12\"\n" +
	"\x05ports\x18\a \x03(\v2\f.weaver.PortR\x05ports\x12/\n" +
	"\bsidecars\x18\b \x03(\v2\x13.weaver.SidecarSpecR\bsidecars\x12%\n" +
	"\x0erestart_policy\x18\t \x01(\tR\rrestartPolicy\x123\n" +
	"\tplacement\x18\n" +
	" \x01(\v2\x15.weaver.PlacementSpecR\tplacement\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x10ResourceRequests\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\tR\x03gpu\"|\n" +
	"\vVolumeMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12\x1d\n" +
	"\n" +
	"content_id\x18\x04 \x01(\tR\tcontentId\"]\n" +
	"\x04Port\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xcd\x01\n" +
	"\vSidecarSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12.\n" +
	"\x03env\x18\x05 \x03(\v2\x1c.weaver.SidecarSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x02\n" +
	"\rPlacementSpec\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12F\n" +
	"\vnode_labels\x18\x04 \x03(\v2%.weaver.PlacementSpec.NodeLabelsEntryR\n" +
	"nodeLabels\x124\n" +
	"\vtolerations\x18\x05 \x03(\v2\x12.weaver.TolerationR\vtolerations\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\n" +
	"Toleration\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x04 \x01(\tR\x06effect\"\xd2\x03\n" +
	"\x0eWorkloadStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12;\n" +
	"\vfinish_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishTime\x12#\n" +
	"\rrestart_count\x18\x06 \x01(\x05R\frestartCount\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x12!\n" +
	"\ftailscale_ip\x18\t \x01(\tR\vtailscaleIp\x12!\n" +
	"\fcontainer_id\x18\n" +
	" \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vsnapshot_id\x18\v \x01(\tR\n" +
	"snapshotId\x12?\n" +
	"\rlast_snapshot\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\flastSnapshot2\xea\a\n" +
	"\rWeaverService\x12O\n" +
	"\x0eCreateWorkload\x12\x1d.weaver.CreateWorkloadRequest\x1a\x1e.weaver.CreateWorkloadResponse\x12F\n" +
	"\vGetWorkload\x12\x1a.weaver.GetWorkloadRequest\x1a\x1b.weaver.GetWorkloadResponse\x12L\n" +
	"\rListWorkloads\x12\x1c.weaver.ListWorkloadsRequest\x1a\x1d.weaver.ListWorkloadsResponse\x12G\n" +
	"\x0eDeleteWorkload\x12\x1d.weaver.DeleteWorkloadRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rListProviders\x12\x16.google.protobuf.Empty\x1a\x1d.weaver.ListProvidersResponse\x12[\n" +
	"\x12GetProviderRegions\x12!.weaver.GetProviderRegionsRequest\x1a\".weaver.GetProviderRegionsResponse\x12j\n" +
	"\x17GetProviderMachineTypes\x12&.weaver.GetProviderMachineTypesRequest\x1a'.weaver.GetProviderMachineTypesResponse\x12P\n" +
	"\x12GetSchedulerStatus\x12\x16.google.protobuf.Empty\x1a\".weaver.GetSchedulerStatusResponse\x12U\n" +
	"\x10ScheduleWorkload\x12\x1f.weaver.ScheduleWorkloadRequest\x1a .weaver.ScheduleWorkloadResponse\x12[\n" +
	"\x12GetRecommendations\x12!.weaver.GetRecommendationsRequest\x1a\".weaver.GetRecommendationsResponse\x12N\n" +
	"\x11GetSchedulerStats\x12\x16.google.protobuf.Empty\x1a!.weaver.GetSchedulerStatsResponse\x12B\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1b.weaver.HealthCheckResponseB\x1cZ\x1afabric/proto/weaver;weaverb\x06proto3"

var (
	file_weaver_internal_grpc_weaver_proto_rawDescOnce sync.Once
	file_weaver_internal_grpc_weaver_proto_rawDescData []byte
)

func file_weaver_internal_grpc_weaver_proto_rawDescGZIP() []byte {
	file_weaver_internal_grpc_weaver_proto_rawDescOnce.Do(func() {
		file_weaver_internal_grpc_weaver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weaver_internal_grpc_weaver_proto_rawDesc), len(file_weaver_internal_grpc_weaver_proto_rawDesc)))
	})
	return file_weaver_internal_grpc_weaver_proto_rawDescData
}

var file_weaver_internal_grpc_weaver_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_weaver_internal_grpc_weaver_proto_goTypes = []any{
	(*CreateWorkloadRequest)(nil),           // 0: weaver.CreateWorkloadRequest
	(*CreateWorkloadResponse)(nil),          // 1: weaver.CreateWorkloadResponse
	(*GetWorkloadRequest)(nil),              // 2: weaver.GetWorkloadRequest
	(*GetWorkloadResponse)(nil),             // 3: weaver.GetWorkloadResponse
	(*ListWorkloadsRequest)(nil),            // 4: weaver.ListWorkloadsRequest
	(*ListWorkloadsResponse)(nil),           // 5: weaver.ListWorkloadsResponse
	(*DeleteWorkloadRequest)(nil),           // 6: weaver.DeleteWorkloadRequest
	(*ListProvidersResponse)(nil),           // 7: weaver.ListProvidersResponse
	(*GetProviderRegionsRequest)(nil),       // 8: weaver.GetProviderRegionsRequest
	(*GetProviderRegionsResponse)(nil),      // 9: weaver.GetProviderRegionsResponse
	(*GetProviderMachineTypesRequest)(nil),  // 10: weaver.GetProviderMachineTypesRequest
	(*GetProviderMachineTypesResponse)(nil), // 11: weaver.GetProviderMachineTypesResponse
	(*MachineType)(nil),                     // 12: weaver.MachineType
	(*GetSchedulerStatusResponse)(nil),      // 13: weaver.GetSchedulerStatusResponse
	(*ScheduleWorkloadRequest)(nil),         // 14: weaver.ScheduleWorkloadRequest
	(*ScheduleWorkloadResponse)(nil),        // 15: weaver.ScheduleWorkloadResponse
	(*GetRecommendationsRequest)(nil),       // 16: weaver.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil),      // 17: weaver.GetRecommendationsResponse
	(*ScheduleRecommendation)(nil),          // 18: weaver.ScheduleRecommendation
	(*GetSchedulerStatsResponse)(nil),       // 19: weaver.GetSchedulerStatsResponse
	(*PlacementConstraints)(nil),            // 20: weaver.PlacementConstraints
	(*HealthCheckResponse)(nil),             // 21: weaver.HealthCheckResponse
	(*Workload)(nil),                        // 22: weaver.Workload
	(*WorkloadSpec)(nil),                    // 23: weaver.WorkloadSpec
	(*ResourceRequests)(nil),                // 24: weaver.ResourceRequests
	(*VolumeMount)(nil),                     // 25: weaver.VolumeMount
	(*Port)(nil),                            // 26: weaver.Port
	(*SidecarSpec)(nil),                     // 27: weaver.SidecarSpec
	(*PlacementSpec)(nil),                   // 28: weaver.PlacementSpec
	(*Toleration)(nil),                      // 29: weaver.Toleration
	(*WorkloadStatus)(nil),                  // 30: weaver.WorkloadStatus
	nil,                                     // 31: weaver.CreateWorkloadRequest.LabelsEntry
	nil,                                     // 32: weaver.CreateWorkloadRequest.AnnotationsEntry
	nil,                                     // 33: weaver.ListWorkloadsRequest.LabelSelectorEntry
	nil,                                     // 34: weaver.GetSchedulerStatsResponse.WorkloadsByProviderEntry
	nil,                                     // 35: weaver.PlacementConstraints.NodeLabelsEntry
	nil,                                     // 36: weaver.Workload.LabelsEntry
	nil,                                     // 37: weaver.Workload.AnnotationsEntry
	nil,                                     // 38: weaver.WorkloadSpec.EnvEntry
	nil,                                     // 39: weaver.SidecarSpec.EnvEntry
	nil,                                     // 40: weaver.PlacementSpec.NodeLabelsEntry
	(*timestamppb.Timestamp)(nil),           // 41: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 42: google.protobuf.Empty
}
var file_weaver_internal_grpc_weaver_proto_depIdxs = []int32{
	23, // 0: weaver.CreateWorkloadRequest.spec:type_name -> weaver.WorkloadSpec
	31, // 1: weaver.CreateWorkloadRequest.labels:type_name -> weaver.CreateWorkloadRequest.LabelsEntry
	32, // 2: weaver.CreateWorkloadRequest.annotations:type_name -> weaver.CreateWorkloadRequest.AnnotationsEntry
	30, // 3: weaver.CreateWorkloadResponse.status:type_name -> weaver.WorkloadStatus
	41, // 4: weaver.CreateWorkloadResponse.created_at:type_name -> google.protobuf.Timestamp
	22, // 5: weaver.GetWorkloadResponse.workload:type_name -> weaver.Workload
	33, // 6: weaver.ListWorkloadsRequest.label_selector:type_name -> weaver.ListWorkloadsRequest.LabelSelectorEntry
	22, // 7: weaver.ListWorkloadsResponse.workloads:type_name -> weaver.Workload
	12, // 8: weaver.GetProviderMachineTypesResponse.machine_types:type_name -> weaver.MachineType
	23, // 9: weaver.ScheduleWorkloadRequest.spec:type_name -> weaver.WorkloadSpec
	20, // 10: weaver.ScheduleWorkloadRequest.constraints:type_name -> weaver.PlacementConstraints
	23, // 11: weaver.GetRecommendationsRequest.spec:type_name -> weaver.WorkloadSpec
	20, // 12: weaver.GetRecommendationsRequest.constraints:type_name -> weaver.PlacementConstraints
	18, // 13: weaver.GetRecommendationsResponse.recommendations:type_name -> weaver.ScheduleRecommendation
	34, // 14: weaver.GetSchedulerStatsResponse.workloads_by_provider:type_name -> weaver.GetSchedulerStatsResponse.WorkloadsByProviderEntry
	35, // 15: weaver.PlacementConstraints.node_labels:type_name -> weaver.PlacementConstraints.NodeLabelsEntry
	29, // 16: weaver.PlacementConstraints.tolerations:type_name -> weaver.Toleration
	41, // 17: weaver.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	36, // 18: weaver.Workload.labels:type_name -> weaver.Workload.LabelsEntry
	37, // 19: weaver.Workload.annotations:type_name -> weaver.Workload.AnnotationsEntry
	23, // 20: weaver.Workload.spec:type_name -> weaver.WorkloadSpec
	30, // 21: weaver.Workload.status:type_name -> weaver.WorkloadStatus
	41, // 22: weaver.Workload.created_at:type_name -> google.protobuf.Timestamp
	41, // 23: weaver.Workload.updated_at:type_name -> google.protobuf.Timestamp
	41, // 24: weaver.Workload.deleted_at:type_name -> google.protobuf.Timestamp
	38, // 25: weaver.WorkloadSpec.env:type_name -> weaver.WorkloadSpec.EnvEntry
	24, // 26: weaver.WorkloadSpec.resources:type_name -> weaver.ResourceRequests
	25, // 27: weaver.WorkloadSpec.volumes:type_name -> weaver.VolumeMount
	26, // 28: weaver.WorkloadSpec.ports:type_name -> weaver.Port
	27, // 29: weaver.WorkloadSpec.sidecars:type_name -> weaver.SidecarSpec
	28, // 30: weaver.WorkloadSpec.placement:type_name -> weaver.PlacementSpec
	39, // 31: weaver.SidecarSpec.env:type_name -> weaver.SidecarSpec.EnvEntry
	40, // 32: weaver.PlacementSpec.node_labels:type_name -> weaver.PlacementSpec.NodeLabelsEntry
	29, // 33: weaver.PlacementSpec.tolerations:type_name -> weaver.Toleration
	41, // 34: weaver.WorkloadStatus.start_time:type_name -> google.protobuf.Timestamp
	41, // 35: weaver.WorkloadStatus.finish_time:type_name -> google.protobuf.Timestamp
	41, // 36: weaver.WorkloadStatus.last_snapshot:type_name -> google.protobuf.Timestamp
	0,  // 37: weaver.WeaverService.CreateWorkload:input_type -> weaver.CreateWorkloadRequest
	2,  // 38: weaver.WeaverService.GetWorkload:input_type -> weaver.GetWorkloadRequest
	4,  // 39: weaver.WeaverService.ListWorkloads:input_type -> weaver.ListWorkloadsRequest
	6,  // 40: weaver.WeaverService.DeleteWorkload:input_type -> weaver.DeleteWorkloadRequest
	42, // 41: weaver.WeaverService.ListProviders:input_type -> google.protobuf.Empty
	8,  // 42: weaver.WeaverService.GetProviderRegions:input_type -> weaver.GetProviderRegionsRequest
	10, // 43: weaver.WeaverService.GetProviderMachineTypes:input_type -> weaver.GetProviderMachineTypesRequest
	42, // 44: weaver.WeaverService.GetSchedulerStatus:input_type -> google.protobuf.Empty
	14, // 45: weaver.WeaverService.ScheduleWorkload:input_type -> weaver.ScheduleWorkloadRequest
	16, // 46: weaver.WeaverService.GetRecommendations:input_type -> weaver.GetRecommendationsRequest
	42, // 47: weaver.WeaverService.GetSchedulerStats:input_type -> google.protobuf.Empty
	42, // 48: weaver.WeaverService.HealthCheck:input_type -> google.protobuf.Empty
	1,  // 49: weaver.WeaverService.CreateWorkload:output_type -> weaver.CreateWorkloadResponse
	3,  // 50: weaver.WeaverService.GetWorkload:output_type -> weaver.GetWorkloadResponse
	5,  // 51: weaver.WeaverService.ListWorkloads:output_type -> weaver.ListWorkloadsResponse
	42, // 52: weaver.WeaverService.DeleteWorkload:output_type -> google.protobuf.Empty
	7,  // 53: weaver.WeaverService.ListProviders:output_type -> weaver.ListProvidersResponse
	9,  // 54: weaver.WeaverService.GetProviderRegions:output_type -> weaver.GetProviderRegionsResponse
	11, // 55: weaver.WeaverService.GetProviderMachineTypes:output_type -> weaver.GetProviderMachineTypesResponse
	13, // 56: weaver.WeaverService.GetSchedulerStatus:output_type -> weaver.GetSchedulerStatusResponse
	15, // 57: weaver.WeaverService.ScheduleWorkload:output_type -> weaver.ScheduleWorkloadResponse
	17, // 58: weaver.WeaverService.GetRecommendations:output_type -> weaver.GetRecommendationsResponse
	19, // 59: weaver.WeaverService.GetSchedulerStats:output_type -> weaver.GetSchedulerStatsResponse
	21, // 60: weaver.WeaverService.HealthCheck:output_type -> weaver.HealthCheckResponse
	49, // [49:61] is the sub-list for method output_type
	37, // [37:49] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_weaver_internal_grpc_weaver_proto_init() }
func file_weaver_internal_grpc_weaver_proto_init() {
	if File_weaver_internal_grpc_weaver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weaver_internal_grpc_weaver_proto_rawDesc), len(file_weaver_internal_grpc_weaver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weaver_internal_grpc_weaver_proto_goTypes,
		DependencyIndexes: file_weaver_internal_grpc_weaver_proto_depIdxs,
		MessageInfos:      file_weaver_internal_grpc_weaver_proto_msgTypes,
	}.Build()
	File_weaver_internal_grpc_weaver_proto = out.File
	file_weaver_internal_grpc_weaver_proto_goTypes = nil
	file_weaver_internal_grpc_weaver_proto_depIdxs = nil
}
